### ISSUE TITLE
confighooks Python Amazon Linux 2 - no way to set execute permissions

### ISSUE THREAD

**Issue by techwatershed** [aws/elastic-beanstalk-roadmap#110] opened 2020-10-20 15:32 UTC
Hello,

I try to execute a run_collectstatic.sh file in .platform/**config**hooks/predeploy during **configuration deployment** (not application deployment, [Configuration deployment hooks](https://github.com/awsdocs/aws-elastic-beanstalk-developer-guide/blob/master/doc_source/platforms-linux-extend.md#configuration-deployment-platform-hooks))

My files:
.platform/**confighooks**/predeploy/run_collectstatics.sh:
```
#!/usr/bin/env bash
source /var/app/venv/*/bin/activate
python manage.py collectstatic --noinput
```

.ebextensions/01_permission.config:
```
container_commands:  
    01_change_mode_of_hooks_file:
        command: chmod +x .platform/hooks/predeploy/run_collectstatics.sh
    02_change_mode_of_confighooks_file:
        command: chmod +x .platform/confighooks/predeploy/run_collectstatics.sh
```

But the configuration deployment fail with the following error (the application deployment is OK):
`Error: Command .platform/confighooks/predeploy/run_collectstatics.sh failed with error fork/exec .platform/confighooks/predeploy/run_collectstatics.sh: permission denied`

It seems that container_commands is not executed during configuration deployment. How can I change the chmod of the file for configuration deployment ?
Any alternative ?

_Originally posted by @appli-intramuros in https://github.com/aws/elastic-beanstalk-roadmap/issues/15#issuecomment-694908240_

**Comment by rzwink** [comment] 2020-10-20 21:06
I was having the same issue and then stumbled on this page which helped:  https://forums.aws.amazon.com/thread.jspa?threadID=321653

For me, the presence of CRLF instead of just LF in my collect_statis.sh made the script fail.  I saved again in unix style and set git to not override 

`git config --global core.autocrlf input`

and things started working again

**Comment by saranshsingh1** [comment] 2021-01-14 08:05
I can confirm that during the configuration deployment phase, none of the files from the `.ebextensions` folder are executed.

Only the hooks present in `.platform/configdeploy/*` folder are executed.

I thought the `.ebextensions` folder was not extracted or it was missing but there is a step in the `/var/log/eb-engine.log` that mentions `Executing instruction: CleanEbExtensions`. So the same steps as `appdeploy` are implemented *but* the files in the `.ebextensions` are **definitely** ignored.

This should not be the case and the documentation is not clear on that.

@techwatershed During the time of application deployment, I had to make the files in the `.platform/configdeploy/*` folder executable, so that during `config-deploy`, those same files can be executed as root.

Not the best solution, since Beanstalk *should* run the `.ebextensions` files as well, but for now it works.

**Comment by samiveikko** [comment] 2021-04-15 23:12
If you are developing in windows environment, script files inside .platform directory doesn't have execution rights (chmod) by default. You could use `git update-index --chmod=-x path/to/file` command to set execution rights for the script files inside .platform directory. That right remains also in config updates.

**Comment by meidikawardana** [comment] 2021-07-30 09:07
I came into this issue today at my work, and in the end the solution for me was to add each .sh file in .platform folder the execute permission, for example run `chmod +x [file]` one by one. 

This method even explained in the documentation: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html
![image](https://user-images.githubusercontent.com/2024380/127629764-9012739d-2875-446a-a9ba-9e34943f37a9.png)

And about .ebextensions, the doc in the same page explains:
![image](https://user-images.githubusercontent.com/2024380/127629925-bd168da8-0370-4a64-8065-2e6a4c270318.png)
For me, I will try my hardest to stay away from using .ebextensions folder from now on.

**Comment by PHPGuus** [comment] 2021-09-07 06:24
AWS Support Case 8732486381 where Ashish and I worked our way through this issue, and left it to the AWS EB product team to come up with a solution.

Synopsis:
Even after doing all you need to do (`chmod +x`, `git chmod`, `dos2unix` to make sure you LF line separators rather than CRLF) it appears, at least on Windows 10 Home, that the awsebcli (3.20.1 (Python 3.9.4)) removes the execution bit from the *confighooks* directory (oddly, it leaves the execution bits in tact in the *hooks* directory). You can verify this by running an `eb deploy` with a new version tag and then downloading that version from the Application versions in the EB Management console and extracting that archive on a "trusted" (Linux :D) platform. The execution bit has vanished.

The only workable workaround I found is to run `eb deploy` (eb version 3.20.1 (Python 3.9.4)) from WSL2. (You can, of course, check in all your changes (commit + push) and then start a full (virtual or physical) Linux environment where you checkout those committed changes, and run `eb deploy` but that is hardly "workable" in that it would take too much time.)

I'll scavenge the interwebs for threads about this issue, and update as many as I can with the above information, just so that folks can move on until the EB Product Team decides that this issue is going to be resolved.

**Comment by 1tonyca** [comment] 2022-05-16 15:48
https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/platforms-linux-extend.html

For all Amazon Linux 2 based platforms versions that were released on or after April 29, 2022, Elastic Beanstalk automatically grants execute permissions to all of the platform hook scripts. In this case you don't have to manually grant execute permissions. For a list of these platform versions, refer to the [April 29, 2022 - Linux platform ](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2022-04-29-linux.html#release-2022-04-29-linux.platforms)release notes in the AWS Elastic Beanstalk Release Notes Guide.

**Closed as completed by 1tonyca** 2022-05-16 15:48 UTC
